CREATE DATABASE IF NOT EXISTS mydatabase;

USE mydatabase;

CREATE TABLE IF NOT EXISTS register (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS muebles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  puestocantidad INT NOT NULL,
  tipoServicio VARCHAR(255) NOT NULL,
  tipoMaterial VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  session_id VARCHAR(255) PRIMARY KEY,
  expires DATETIME NOT NULL,
  data TEXT NOT NULL
);
